apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector: 
    app: python-app
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  