apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector: 
    app: {{ .Values.appName }}
  type: LoadBalancer
  ports:
    - port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
      protocol: TCP
      name: http
  
