name: Build And Update Image

on:
  push:
    paths:
      - app.py
      - test_app.py
      - Dockerfile
      - requirements.txt

jobs:
  build-and-push-and-update:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: "flask-hello-world"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
                    
    - name: Build Docker image
      run: docker build -t $DOCKER_IMAGE_NAME .
    
    - name: Test Docker image
      run: |
        docker run --rm $DOCKER_IMAGE_NAME python test_app.py

    - name: Get Current Date and Time
      id: date
      run: |
          echo "DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Update Tag in values.yaml
      run: |
          DATE_TAG=${{ env.DATE }}
          sed -i "s|\(tag: \).*|\1${DATE_TAG}|g" Deployment/values.yaml

    - name: Tag Docker image
      run: docker tag $DOCKER_IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:$DATE_TAG

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:$DATE_TAG
 
    - name: Push Update to Git
      run: |
        git config --global user.name "persiidan"
        git config --global user.email ${{ secrets.Git_Email }}
        git add Deployment/values.yaml
        git  commit -m "Update tag to ${{ env.DATE }}"
        git push origin main
