name: Build, Test, and Push to Docker Hub

# on:
#   push:
#     paths:
#       - app.py
#       - test_app.py
#       - Dockerfile
#       - requirements.txt
#   pull_request:
#     paths:
#       - app.py
#       - test_app.py
#       - Dockerfile
#       - requirements.txt

on:
  push:
    branches: 
     - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: docker build -t flask-hello-world .

    - name: Test Docker image
      run: |
        docker run --rm flask-hello-world python test_app.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      run: docker tag flask-hello-world idanpersi/flask-hello-world:latest

    - name: Push to Docker Hub
      run: docker push idanpersi/flask-hello-world:latest
