name: Update image Tag

on:
  workflow_run:
    workflows:
      - Build, Test, and Push to Docker Hub # Name of the docker image workflow
    types:
      - completed


jobs:
  update-helm-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "persiidan"
        git config --global user.email ${{ secrets.Git_Email }}
                
    - name: Get Current Date and Time
      id: date
      run: |
          echo "DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Update Tag in values.yaml
      run: |
          DATE_TAG=${{ env.DATE }}
          sed -i "s|\(tag: \).*|\1${DATE_TAG}|g" Deployment/values.yaml

    - name: Commit and push updated chart version
      run: |
        git add Deployment/values.yaml
        git  commit -m "Update tag to ${{ env.DATE }}"
        git push origin main
